version: '3.8'

services:

  db: 
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: todo_db
    
    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: